### ISSUE TITLE
Integrate with seaborn

### ISSUE THREAD

**Issue by nateGeorge** [cphyc/matplotlib-label-lines#25] opened 2021-01-04 04:08 UTC
I'd really like this to work with the seaborn library. I haven't looked into how seaborn is managing labels, but here is an example of how to label something with a seaborn plot:

```python
import pandas as pd
import seaborn as sns
from labellines import labelLines

gb = pd.read_csv('https://pastebin.com/raw/cJnxzxkY', parse_dates=['InvoiceDate'], infer_datetime_format=True)
ax = sns.lineplot(data=gb, x='InvoiceDate', y='Total', hue='BillingCountry', legend=False)
# labelLines(plt.gcf().gca().get_lines()[:3])  # doesn't work, and only first 3 lines have data -- last 3 are empty
for (i, line), label in zip(enumerate(ax.get_lines()[:3]), ['Canada', 'USA', 'France']):
    labelLine(line, x=gb['InvoiceDate'][i * 20 + 50], label=label)
```

**Comment by cphyc** [comment] 2021-01-11 13:38
That indeed looks like a bug. I am not using seaborn, but I am open to PR to fix this!

**Comment by cphyc** [comment] 2021-01-15 11:40
Coming back to this issue, the problem is that by default seaborn does not label its lines, so that `labelLines` cannot infer them. The workaround is to manually label them as per your example.

I'm closing this as it probably won't fix (unless the labels are hidden somewhere?).

**Closed by cphyc** 2021-01-15 11:40 UTC
