### ISSUE TITLE
Labels are not aligned in some cases

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [cphyc/matplotlib-label-lines#33] opened 2021-02-01 10:12 UTC
![image](https://user-images.githubusercontent.com/40028739/106445481-5d11bd80-647f-11eb-891d-6ac35b8e8c3c.png)

**How to reproduce**

```python
import matplotlib.pyplot as plt
from labellines import *


x = [0, 1e-9, 5e-7]

y = [0, 3e21, 1e21]

plt.plot(x, y, label="label")

labelLines(plt.gca().get_lines(), zorder=2.5, xvals=[3e-7])
plt.show()
```

**Comment by RemDelaporteMathurin** [comment] 2021-02-01 10:20
@cphyc I've now added code to reproduce what I think is a bug ?

**Comment by RemDelaporteMathurin** [comment] 2021-02-01 10:22
Note that the following produces the expected output.
This probably has something to do with the scale of values ?
```python
import matplotlib.pyplot as plt
from labellines import *


x = [0, 1e-2, 5]

y = [0, 3, 1]

plt.plot(x, y, label="label")

labelLines(plt.gca().get_lines(), zorder=2.5, xvals=[3])
plt.show()
```
![image](https://user-images.githubusercontent.com/40028739/106445662-99ddb480-647f-11eb-841d-ac9e31d940ee.png)

**Comment by cphyc** [comment] 2021-02-01 10:22
It seems to be working on my side. Could you mention which version of the package you use + which matplotlib version?

![image](https://user-images.githubusercontent.com/5411875/106445768-b7ab1980-647f-11eb-928b-a84cbbd9c027.png)

**Comment by RemDelaporteMathurin** [comment] 2021-02-01 10:26
I'm using matplotlib 3.3.3 and the latest version pypi version of the package so 0.3.9 according to https://pypi.org/project/matplotlib-label-lines/

**Comment by RemDelaporteMathurin** [comment] 2021-02-01 10:31
Also, not assigning a custom xvals doesn't produce the bug: 
```python
import matplotlib.pyplot as plt
from labellines import *


x = [0, 1e-2, 5]

y = [0, 3e21, 1e21]

plt.plot(x, y, label="label")

labelLines(plt.gca().get_lines(), zorder=2.5)
plt.show()
```

**Comment by cphyc** [comment] 2021-02-01 10:31
OK I managed to reproduce the bug, though I don't quite understand how

**Comment by RemDelaporteMathurin** [comment] 2021-02-01 13:50
> OK I managed to reproduce the bug, though I don't quite understand how

Is the bug in the latest version too then ?

**Comment by cphyc** [comment] 2021-02-01 15:19
Yes it happens on the latest version as well.

I am wondering whether it may not be due to matplotlib changing the axis scale of one the two axes and the code not getting it right. Could you check that manually setting the xlim/ylim of the plot *before* adding the label line solves the issue?

**Comment by RemDelaporteMathurin** [comment] 2021-02-02 07:37
```python
import matplotlib.pyplot as plt
from labellines import *


x = [0, 1e-9, 5e-7]

y = [0, 3e21, 1e21]

plt.plot(x, y, label="label")
plt.xlim(-1e-7, 6e-7)
plt.ylim(-0.5e21, 3.2e21)
labelLines(plt.gca().get_lines(), zorder=2.5, xvals=[3e-7])
plt.show()
```
![image](https://user-images.githubusercontent.com/40028739/106567307-ea154f00-6531-11eb-9045-abd26f552050.png)

This produces the expected behaviour

**Comment by cphyc** [comment] 2021-02-02 20:16
OK. So this seems to be related to #36 . I am quite unsure how to fix this without a major refactor of the code.

**Comment by cphyc** [comment] 2021-02-03 13:43
Closing it for now as it seems to be a duplicate of #36 . We should re-open it once the other one is fixed and if this one persists.

**Closed by cphyc** 2021-02-03 13:43 UTC

**Comment by RemDelaporteMathurin** [comment] 2021-02-08 09:08
@cphyc I thought about it and it seems that this issue isn't fully related to #36 since the bug also occur when the axes limits are untouched (see initial post)

```python
import matplotlib.pyplot as plt
from labellines import *


x = [0, 1e-9, 5e-7]

y = [0, 3e21, 1e21]

plt.plot(x, y, label="label")

labelLines(plt.gca().get_lines(), zorder=2.5, xvals=[3e-7])
plt.show()
```
